name: Code Quality checks

on:
  pull_request:
    # branches:
      # - main
  push:
    # branches:
      # - main

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install -D

      - name: Check formatting with Prettier
        run: npm run prettier:check:ci

      - name: Auto-commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        with:
          commit_message: "Prettier: format files"
