name: Code Quality checks

on:
  pull_request:
  push:

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Check formatting with Prettier
      - run: npm -D
      - run: npm prettier:check:ci
      - uses: stefanzweifel/git-auto-commit-action@v5
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        with:
          commit_message: "Prettier: format files"